// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[example]")
{
    REQUIRE(isAlphabetical("alex", "bob") == 1);
    REQUIRE(isAlphabetical("alex", "Bob") == 1);
    REQUIRE(isAlphabetical("alex", "alexander") == 1);
    REQUIRE(isAlphabetical("alex", "ALEX") == 1);
    REQUIRE(isAlphabetical("Bob", "bob") == 1);
    REQUIRE(isAlphabetical("Bob", "alexa") == 0);
    REQUIRE(isAlphabetical("bob", "Alexa") == 0);

}

